// 嵌入式领域配置
const config = {
  name: 'embedded',
  skillCategory: {
    'embedded-debugger-framework': 'debug', 'cmbacktrace-debug': 'debug',
    'arm-interrupt-exception': 'debug', 'arm-memory-architecture': 'debug',
    'rtos-debug': 'debug', 'freertos-module': 'debug', 'arm-core-registers': 'debug',
    'build-cmake': 'build', 'build-keil': 'build', 'build-iar': 'build',
    'build-idf': 'build', 'build-platformio': 'build', 'code-porting': 'build',
    'debug-gdb-openocd': 'build', 'flash-jlink': 'build', 'flash-openocd': 'build',
    'serial-monitor': 'monitor', 'uart-module': 'monitor',
    'can-debug': 'comm', 'i2c-bus': 'comm', 'spi-bus': 'comm',
    'ble-module': 'comm', 'wifi-module': 'comm', 'mqtt-module': 'comm',
    'peripheral-driver': 'driver', 'stm32-hal-development': 'driver',
    'timer-module': 'driver', 'adc-module': 'driver', 'dma-module': 'driver',
    'usb-module': 'driver', 'motor-control': 'driver',
    'lowpower-design': 'system', 'bootloader-design': 'system',
    'ota-update-system': 'system', 'watchdog-module': 'system',
    'static-analysis': 'quality', 'coding-standards': 'quality', 'map-analyzer': 'quality',
    'embedded-architect': 'arch',
    'fatfs-module': 'middleware', 'aes-module': 'middleware', 'rsa-module': 'middleware',
    'crc-module': 'middleware', 'lvgl-module': 'middleware', 'dsp-module': 'middleware',
    'segger-rtt-module': 'middleware', 'elog-module': 'middleware',
    'knowledge-base-search': 'knowledge',
  },
  categoryPrompts: {
    debug: '优先定位症状根因，再实现修复',
    build: '确保构建脚本和链接配置正确',
    comm: '按协议规范逐字节验证，注意时序和错误处理',
    driver: '封装 init/read_write/irq_callback 三层 API',
    system: '分析系统级约束，量化方案权衡',
    quality: '逐行审查代码，记录违规项',
    middleware: '检查接口对齐和依赖版本兼容',
  },
  troubleshootingMap: [
    { keywords: ['i2c', 'busy'], step1: '9脉冲法/SWRST复位I2C外设', step2: '检查SCL/SDA电平' },
    { keywords: ['hardfault'], step1: 'CmBacktrace栈回溯', step2: '解码CFSR/BFSR/UFSR' },
    { keywords: ['uart', '乱码'], step1: '核对波特率/数据位/ORE标志', step2: '检查串口线序' },
    { keywords: ['spi', 'bsy'], step1: 'CR1复位SPI外设', step2: '检查SR状态位' },
  ],
  verificationCriteria: '来源可信度: 参考手册(1.0) > HAL源码(0.85) > 社区(0.50) > 论坛(0.30)',
  security: { enabled: true, domain: 'embedded', preflight_rules: { check_high_risk: true, check_file_permissions: true, check_blacklist: true, check_embedded_constraints: true } },
}
